[tools]
node = "24.18.0"

[tasks.clean]
description = "Full node clean, install, build and test"
run = '''

  # Reset node modules.
  rm -rvf node_modules
  npm cache clean --force
  rm -v package-lock.json || true

  # Verify package proxying via Nexus.
  npm --ignore-scripts --verbose install
  npm cache verify --verbose

'''
